### ISSUE TITLE
install lister on windows

### ISSUE THREAD

**Issue by B4RD4k** [summitt/lister#1]
Hey, 

I tried to install Lister on windows without luck cuase of the pypcap library comptability or sth,
can you advice?

10x

**Comment by summitt** [comment]
It took me a while to get it working on windows. I think i had to install everything using the new bash-on-windows from the dev preview. I'll look later and see if i can find my steps.

**Comment by summitt** [comment]
Hey @eranvak , sorry i have not gotten back to you about this. The never version of Nope (v1.5) will have this built in so you won't need to run this separate script anymore. If you have winpcap or libpcap installed then Nope will display this data in a table for you. I should hopefully have v1.5 completed before the end of the week.

**Comment by B4RD4k** [comment]
10x bro :)
